openapi: 3.0.3
info:
  title: Digital Staff Passport API
  version: __VERSION__  # Automatically populated by `scripts/calculate_version.py` at release-time
  description: |
    ## Overview
    Use this API standard to build an API that Digital Staff Passport (DSP) can use to get NHS employee records from your system.

    DSP can then allow the employee to pass the information on to their new employer.

    The standard includes:
    - searching for an employee in the source system
    - getting employee records from the source system

    The standard currently does not include:
    - details of how security will work
    - details of the required service level for the source system
    - support for multiple organisations - it assumes the source system only holds data for a single NHS organisation
    - support for 'pagination' of search results in the event of there being more than 50 matching employees
    - the ability to update employee records in the source system
    
    ## Who can use this API standard
    You can only use this API standard if you are integrating your system with Digital Staff Passport.

    ## Status
    This API standard is a [draft](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses),
    meaning it is under development and might be subject to breaking changes.

    We are currently running a pilot with one external system and iterating the standard as we proceed.

    ## Service level
    Details to follow.

    ## Technology
    This API standard is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).

    It does not conform to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir)
    global standard for health care data exchance because it is not a clinical API, it relates to workforce.

    ## Network access
    Your API must be available on the internet.
    
    ## Security and authorisation
    Details to follow.

    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    For details of specific errors, see the 'Response' section for each operation. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

    ## Environments and testing
    You'll need to:
    - deploy your API into an environment that we can use for integration testing
    - populate that environment with suitable test data

    ## Onboarding
    We are currently running a pilot with one external system, so the API standard is not available for anyone else to onboard just yet. 
    
  contact:
    name: API Management Support
    email: api.management@nhs.net
    url: 'https://digital.nhs.uk/developer/help-and-support'
x-spec-publication:
  try-this-api:
    disabled: true
paths:
  /employees:
    get:
      operationId: search-for-employee
      summary: Search for an employee
      description: |
        This operation returns a list of employees that match the supplied search parameters.

        The following search parameters are supported:
        - first name
        - surname
        - date of birth

        The operation returns a maximum of 50 matching employees.
        If there are more than 50 matches, it returns the first 50.
        There is currently no way of knowing whether there are more than 50 matches.
        In the future we might add pagination.

        All search parameters are optional, but if they are all omitted it is likely to result in a 'too many matches' error.

      parameters:
        - name: firstName
          in: query
          description: The employee's first name.
          required: false
          example: 'Jane'
          schema:
            type: string
        - name: surname
          in: query
          description: The employee's surname.
          required: false
          example: 'Smith'
          schema:
            type: string
        - name: birthDate
          in: query
          description: The employee's date of birth, in the format `yyyy-mm-dd`.
          required: false
          example: '1998-10-22'
          schema:
            type: string
      responses:
        '200':
          description: A completed search. This might contain zero, one or many matching patients.
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 50
                items:
                  $ref: '#/components/schemas/Employee'
              example:
                $ref: components/examples/SearchForAnEmployeeHappyPathResponse.json
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
  /employees/{id}/records:
    get:
      operationId: get-employee-records
      summary: Get employee records
      description: |
        This operation returns a list of all data records available for a given employee.
        The type of records returned depends on the type of system.
        For example, a learning management system would return training records.
      parameters:
        - name: id
          in: path
          description: The employee's primary unique identifier, as used by the source system.
          required: true
          example: '12345'
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeData'
              example:
                employeeId: 1f9a7bb6-6fc7-45ec-9334-03feaed520b4
                timeStamp: '2024-02-23T14:07:36.0390356+00:00'
                records:
                  - statMandSubject: Information Governance and Data Security
                    level: '1'
                    attainmentStatus: ACHIEVED
                    competencyFramework: CSTF
                    competencyName: Information  Governance and Data Security
                    awardingOrg: RHQ
                    renewalPeriod: '2'
                    units: Year
                    learningMethod: Test
                    dateTo: 2023-03-20T00:00Z
                    lastDateAwarded: 2023-11-01T00:00Z
                    proficiencyLevel: 0 - Not Assessed
                    type: CoreSkillsTraining
                  - statMandSubject: Resuscitation
                    level: '2'
                    attainmentStatus: ACHIEVED
                    competencyFramework: CSTF
                    competencyName: Resuscitation Adult Basic Life Support
                    awardingOrg: RHQ
                    renewalPeriod: '1'
                    units: Year
                    learningMethod: Test
                    dateTo: 2024-11-20T00:00Z
                    lastDateAwarded: 2023-11-20T00:00Z
                    proficiencyLevel: 0 - Not Assessed
                    type: CoreSkillsTraining
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
components:
  schemas:
    CoreSkillsTraining:
      type: object
      properties:
        type:
          type: string
          nullable: true
        statMandSubject:
          type: string
          nullable: true
        level:
          type: string
          nullable: true
        attainmentStatus:
          type: string
          nullable: true
        competencyFramework:
          type: string
          nullable: true
        competencyName:
          type: string
          nullable: true
        awardingOrg:
          type: string
          nullable: true
        renewalPeriod:
          type: string
          nullable: true
        units:
          type: string
          nullable: true
        learningMethod:
          type: string
          nullable: true
        dateTo:
          type: string
          nullable: true
        lastDateAwarded:
          type: string
          nullable: true
        proficiencyLevel:
          type: string
          nullable: true
      additionalProperties: false
    Employee:
      type: object
      required:
        - id
        - firstName
        - surname
      properties:
        id:
          description: The employee's primary unique identifier, as used by the source system.
          type: string
        firstName:
          description: The employee's first name.
          type: string
        surname:
          description: The employee's surname.
          type: string
        birthDate:
          description: The employee's date of birth, in the format `yyyy-mm-dd`.
          type: string
        email:
          description: The employee's email address.
          type: string
        esrIdentifier:
          description: The employee's unique identifier in the ESR system.
          type: string
      additionalProperties: false
    EmployeeData:
      type: object
      properties:
        employeeId:
          type: string
          nullable: true
        timeStamp:
          type: string
          nullable: true
        records:
          type: array
          items:
            $ref: '#/components/schemas/CoreSkillsTraining'
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
