openapi: 3.0.3
info:
  title: Digital Staff Passport API
  version: __VERSION__  # Automatically populated by `scripts/calculate_version.py` at release-time
  description: |
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="http://digital.nhs.uk/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is <a href="https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses">in production, beta but internal</a>, meaning the API is not currently available for integration by external third parties. If you want to use it, <a href="https://digital.nhs.uk/developer/help-and-support">contact us</a> and we'll look at making it available.</p></div>
            </div>
        </div>
    </div>

    ## Overview
    TBC
    
    TBC mention that the API is currently not organisation aware.

    ## Who can use this API
    TBC

    ## API status and roadmap
    TBC

    ## Service level
    TBC

    ## Technology
    TBC

    ## Network access
    TBC
    
    ## Security and authorisation
    TBC

    ## Environments and testing
    TBC

    ## Onboarding
    TBC
    
    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

  contact:
    name: API Management Support
    email: api.management@nhs.net
    url: 'https://digital.nhs.uk/developer/help-and-support'
x-spec-publication:
  try-this-api:
    disabled: true
paths:
  /employees:
    get:
      operationId: search-for-employee
      summary: Search for an employee
      description: |
        This operation returns a list of employees that match the supplied search parameters.

        The following search parameters are supported:
        - first name
        - surname
        - date of birth

        The operation returns a maximum of 50 matching employees.
        If there are more than 50 matches, it returns an error, and the user should be told to refine their search criteria.

        All search parameters are optional, but if they are all omitted it is likely to result in a 'too many matches' error.

      tags:
        - Employees
      parameters:
        - name: firstName
          in: query
          description: The employee's first name.
          required: false
          example: "Jane"
          schema:
            type: string
        - name: surname
          in: query
          description: The employee's surname.
          required: false
          example: "Smith"
          schema:
            type: string
        - name: birthDate
          in: query
          description: The employee's date of birth, in the format `yyyy-mm-dd`.
          required: false
          example: "1998-10-22"
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
              example:
                employeeId: '999'
                firstName: John
                lastName: Smith
                identifier: 5e8fe03f-8cc6-4220-ba18-511c9c47366d
                dateOfBirth: '2024-02-23'
                email: another@mail.com
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
  /employees/{employeeId}/records:
    get:
      operationId: get-employee-records
      summary: Get employee records
      description: |
        This operation returns a list of all data records available for a given employee.
        The type of records returned depends on the type of system.
        For example, a learning management system would return training records.
      tags:
        - Employees
      parameters:
        - name: employeeId
          in: path
          description: The id of the employee
          required: true
          schema:
            type: string
        - name: orgCode
          in: header
          description: The organisation code
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeData'
              example:
                employeeId: 1f9a7bb6-6fc7-45ec-9334-03feaed520b4
                timeStamp: '2024-02-23T14:07:36.0390356+00:00'
                records:
                  - statMandSubject: Information Governance and Data Security
                    level: '1'
                    attainmentStatus: ACHIEVED
                    competencyFramework: CSTF
                    competencyName: Information  Governance and Data Security
                    awardingOrg: RHQ
                    renewalPeriod: '2'
                    units: Year
                    learningMethod: Test
                    dateTo: 2023-03-20T00:00Z
                    lastDateAwarded: 2023-11-01T00:00Z
                    proficiencyLevel: 0 - Not Assessed
                    type: CoreSkillsTraining
                  - statMandSubject: Resuscitation
                    level: '2'
                    attainmentStatus: ACHIEVED
                    competencyFramework: CSTF
                    competencyName: Resuscitation Adult Basic Life Support
                    awardingOrg: RHQ
                    renewalPeriod: '1'
                    units: Year
                    learningMethod: Test
                    dateTo: 2024-11-20T00:00Z
                    lastDateAwarded: 2023-11-20T00:00Z
                    proficiencyLevel: 0 - Not Assessed
                    type: CoreSkillsTraining
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error
components:
  schemas:
    CoreSkillsTraining:
      type: object
      properties:
        type:
          type: string
          nullable: true
        statMandSubject:
          type: string
          nullable: true
        level:
          type: string
          nullable: true
        attainmentStatus:
          type: string
          nullable: true
        competencyFramework:
          type: string
          nullable: true
        competencyName:
          type: string
          nullable: true
        awardingOrg:
          type: string
          nullable: true
        renewalPeriod:
          type: string
          nullable: true
        units:
          type: string
          nullable: true
        learningMethod:
          type: string
          nullable: true
        dateTo:
          type: string
          nullable: true
        lastDateAwarded:
          type: string
          nullable: true
        proficiencyLevel:
          type: string
          nullable: true
      additionalProperties: false
    Employee:
      type: object
      properties:
        employeeId:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        identifier:
          type: string
          nullable: true
        dateOfBirth:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    EmployeeData:
      type: object
      properties:
        employeeId:
          type: string
          nullable: true
        timeStamp:
          type: string
          nullable: true
        records:
          type: array
          items:
            $ref: '#/components/schemas/CoreSkillsTraining'
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
