openapi: '3.0.3'
info:
  title: Proxygen API
  version: '__VERSION__' # Computed and injected at build time by `scripts/set_version.py`
  description: |
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="http://digital.nhs.uk/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is <a href="https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses">in production, beta but internal</a>, meaning the API is not currently available for integration by external third parties. If you want to use it, <a href="https://digital.nhs.uk/developer/help-and-support">contact us</a> and we'll look at making it available.</p></div>            
            </div>
        </div>
    </div>

    ## Overview
    Use this API to create and manage resources on NHS England's API Management platform.
    This API is intended for NHS England internal product teams to make services available over the internet.

    You can:
    * Do a thing..
    * And another thing..

    In the future, you will be able to:
    * Do this thing

    ## Who can use this API
    This API is currently for internal NHS England use only.

    ## Related APIs
    Can/should we remove this section?

    ## API status and roadmap
    This API is in [production, beta but internal](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses), meaning:
    * we might make breaking changes, but only if we cannot avoid it, and we will give advance notice
    * it is only available for internal NHS England users

    ## Service level
    This API is a bronze service, meaning it is operational and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.
    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis).

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).
    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    Todo

    ## Environments and testing

    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Development       | `https://proxygen.ptl.api.platform.nhs.uk`                             |
    | Production        | `https://proxygen.prod.api.platform.nhs.uk`                            |


    ### Development environment
    Our development environment:
    * is for developers of the Proxygen service itself
    * is not intended for [integration testing](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing)
    
    ## Onboarding
    This API is for internal NHS England users only. There is no onboarding process for external parties.
    The 'Getting started as an API Producer' section of the API Management NHS England Platforms Confluence space provides instructions on how to engage with us and start using Proxygen.

    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

  license:
    name: MIT
  contact:
    name: API Management Support
    email: api.management@nhs.net

x-spec-publication:
  operation-order:
    # - group: Registration
    #   operations:
    #     - method: POST
    #       path: /registrations
    #     - method: POST
    #       path: /transfer-compatibility-statuses
    #     - method: POST
    #       path: /ehr-requests
    #     - method: POST
    #       path: /ehr-responses
    #     - method: POST
    #       path: /document-responses
    #     - method: POST
    #       path: /ready-to-integrate-statuses
    #     - method: POST
    #       path: /ehr-degrades
    #     - method: POST
    #       path: /ehr-integrations
    #     - method: POST
    #       path: /errors
  try-this-api:
    disabled: true

servers:
  - url: https://proxygen.prod.api.platform.nhs.uk
    description: Production environment.
  - url: https://proxygen.ptl.api.platform.nhs.uk
    description: Development environment.
tags:
  - name: Instances
    description: Endpoints to manage instances of your API 
  - name: Secrets
    description: Endpoints to manage sensitive information (secrets) such as API keys
  - name: Container Registry
    description: Get access details to use the Elastic Container Registry associated with your API 
  - name: Specifications
    description: Endpoints to manage 
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /apis/{api_name}/environments/{environment}/instances/{instance_name}:
    get:
      summary: "Get a specific API Instance"
      operationId: get-instance
      # description: ''
      parameters:
        - name: api_name
          in: path
          description: "..."
          required: true
          schema:
            type: string
            example: "hello-world"
        - name: environment
          in: path
          description: "..."
          required: true
          schema:
            type: string
            enum:
              - internal-dev
              - internal-dev-sandbox
              - internal-qa
              - internal-qa-sandbox
              - ref
              - dev
              - int
              - sandbox
              - prod
        - name: instance_name
          in: path
          description: "..."
          required: true
          schema:
            type: string
            example: "..."
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: components/schemas/proxygen-oas.yaml
              # example:
              #   $ref: components/examples/Patient.json

        # '404':
          
