name: PR Quality Check
run-name: PR Quality Check for ${{ github.event.pull_request.head.ref }} opened by @${{ github.actor }}
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check the branch name references a Jira ticket
      env:
        REF: ${{ github.event.pull_request.head.ref }}
      run: echo "$REF" | grep -i -E -q "(apm-[0-9]+)|(apmspii-[0-9]+)|(adz-[0-9]+)|(amb-[0-9]+)|(amp-[0-9]+)|(dependabot\/)"

    - name: Set TICKET_NAME environment variable
      env:
        REF: ${{ github.event.pull_request.head.ref }}
      run: |
        TICKET_NAME=$(echo "$REF" | grep -i -o '\(apm-[0-9]\+\)\|\(apmspii-[0-9]\+\)\|\(adz-[0-9]\+\)\|\(amb-[0-9]\+\)\|\(amp-[0-9]\+\)' | tr '[:lower:]' '[:upper:]')
        echo "TICKET_NAME=$TICKET_NAME" >> "$GITHUB_ENV"

    - name: Comment on PR with link to JIRA ticket
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          This branch is work on a ticket in the NHS England's API Management JIRA Project:
          # [${{ env.TICKET_NAME }}](https://nhsd-jira.digital.nhs.uk/browse/${{ env.TICKET_NAME}})
        comment_tag: jira-ticket

    - name: Add UAT Portal Deployment Instructions to PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Manually run the [Publish Spec to Bloomreach UAT Portal](https://github.com/NHSDigital/proxygen-api-specification/actions/workflows/publish-uat.yml) to preview specification on the [UAT Portal](https://uat2.nhsd.io/developer/api-catalogue/proxy-generator) (requires VPN).
        comment_tag: uat-deploy
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: Vacuum OpenAPI Spec linter
      uses: eduelias/gha-vacuum@v0.0.1
      with:
        cmd: vacuum lint -d specification/proxygen.yaml
  
