name: Publish Spec to Bloomreach UAT Portal
run-name: Publish ${{ github.ref_name }} (${{ github.actor }})
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - name: Setup Python environment and dependencies
        run: poetry install

      - name: Set OAS info.version to ${{ github.ref_name}}-${{github.sha}}
        run: sed -i 's/__VERSION__/${{ github.ref_name}}-${{github.sha}}/g' specification/proxygen.yaml

      - name: Lint spec
        run: poetry run openapi-spec-validator specification/proxygen.yaml

      - name: Publish to UAT Bloomreach
        run: poetry run proxygen spec publish


